version: '3'
services:
  llmpedia:
    build: .
    env_file:
      - .env
    volumes:
      - ./imgs:/app/imgs
      - ./data:/app/data
      - ./data/arxiv_text:/app/data/arxiv_text
      - ./data/nonllm_arxiv_text:/app/data/nonllm_arxiv_text
      - ./data/arxiv_first_page:/app/data/arxiv_first_page
      - ./data/arxiv_chunks:/app/data/arxiv_chunks
      - ./data/arxiv_large_chunks:/app/data/arxiv_large_chunks
      - /mnt/artifacts/models:/app/ComfyUI/models
      - /mnt/artifacts/models/bertopic:/app/data/bertopic
    ports:
      - "8188:8188"  # ComfyUI interface
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome-stable
      - TZ=America/Los_Angeles