# Selection weights for random tweet type selection
selection:
  default_weights:
    punchline: 0.85
    insight_v5: 0.15
    fable: 0.0
  
# Tweet type definitions
tweet_types:
  insight_v5:
    name: "Insight Thread"
    description: "A thread with paper insights, first page, and links"
    weight: 0.3  # Selection weight for this tweet type (used if no weight set is specified)
    tweets:
      - position: 0
        generator: insight # Generates insight text + art image
      - position: 1
        generator: author # Generates author text
      - position: 2
        generator: links # Generates links text
  
  punchline:
    name: "Punchline Tweet"
    description: "A concise tweet with paper punchline and selected figure"
    weight: 0.7  # Selection weight for this tweet type (used if no weight set is specified)
    tweets:
      - position: 0
        # content:
        #   content_type: "function"
        #   content: "generate_punchline_content"
        #   description: "Paper punchline"
        # images:
        #   - source_type: "function"
        #     source: "select_punchline_image"
        #     description: "Selected figure from paper"
        generator: punchline # Use the combined generator
      - position: 1
        # content:
        #   content_type: "function"
        #   content: "generate_author_tweet"
        #   description: "Author related discussion"
        generator: author # Use the author generator
      - position: 2
        # content:
        #   content_type: "function"
        #   content: "generate_links_content"
        #   description: "Links to paper and resources"
        generator: links # Use the links generator

  fable:
    name: "Fable Tweet"
    description: "A creative fable-style tweet about the paper"
    weight: 0.0  # Selection weight for this tweet type (currently disabled)
    tweets:
      - position: 0
        content:
          content_type: "function"
          content: "generate_fable_content"
          description: "Paper fable"
        images:
          - source_type: "function"
            source: "get_art_image"
            description: "Paper art image"
      - position: 1
        content:
          content_type: "function"
          content: "generate_links_content"
          description: "Links to paper and resources"
      - position: 2
        content:
          content_type: "function"
          content: "generate_author_tweet"
          description: "Related discussion from paper authors" 